{:ok, _} = Application.ensure_all_started(:ex_games_account)
{:ok, _} = Application.ensure_all_started(:ex_games)
{:ok, _} = Application.ensure_all_started(:ex_games_web)
Process.sleep(500)
{:ok, port} = :gen_tcp.listen(0, [])
{:ok, pnum} = :inet.port(port)
IO.inspect(pnum, label: "free port check ok")
children = Supervisor.which_children(ExGamesWebWeb.Endpoint)
IO.inspect(Enum.map(children, &elem(&1, 0)), label: "endpoint children")
http_port = ExGamesWebWeb.Endpoint.config(:http) |> Keyword.get(:port)
IO.inspect(http_port, label: "configured port")
